import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
//! imp Comps
import Header from '../components/Header'
import Footer from '../components/Footer'
//! Context
import { AppStoreProvider } from '../Context'

const poppins = Poppins({ subsets: ['latin'], weight: ['400'] })

export const metadata: Metadata = {
  title: 'Book Store',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <AppStoreProvider>
          <Header />
          {children}
          <Footer />
        </AppStoreProvider>
      </body>
    </html>
  )
}
